[tool.poetry]
name = "langevals-ragas"
version = "0.1.3"
description = "LangEvals Ragas evaluator"
authors = ["Your Name <your.email@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
langevals-core = { path = "../../langevals_core", develop = true }
ragas = "^0.1.7"
langchain-openai = "^0.1.6"
langchain_community = "^0.0.27"
datasets = "^2.18.0"
litellm = "^1.31.3"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.2"
python-dotenv = "^1.0.1"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
